# Numpy tricks

### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [2]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[51, 45, 86, 69],
       [73, 11, 44, 18],
       [93, 28, 64, 55],
       [95, 53, 96, 41],
       [80, 16, 23, 53],
       [ 7,  1, 37, 82]], dtype=int32)

In [4]:
np.sort(a)

array([ 3,  6,  8,  8, 17, 33, 42, 43, 45, 48, 59, 62, 65, 68, 81],
      dtype=int32)

In [5]:
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [6]:
np.sort(a)[::-1]

array([81, 68, 65, 62, 59, 48, 45, 43, 42, 33, 17,  8,  8,  6,  3],
      dtype=int32)

In [7]:
b

array([[51, 45, 86, 69],
       [73, 11, 44, 18],
       [93, 28, 64, 55],
       [95, 53, 96, 41],
       [80, 16, 23, 53],
       [ 7,  1, 37, 82]], dtype=int32)

In [11]:
np.sort(b, axis=1)

array([[45, 51, 69, 86],
       [11, 18, 44, 73],
       [28, 55, 64, 93],
       [41, 53, 95, 96],
       [16, 23, 53, 80],
       [ 1,  7, 37, 82]], dtype=int32)

In [12]:
np.sort(b,axis=0)

array([[ 7,  1, 23, 18],
       [51, 11, 37, 41],
       [73, 16, 44, 53],
       [80, 28, 64, 55],
       [93, 45, 86, 69],
       [95, 53, 96, 82]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [15]:
# code
np.append(a,200)

array([  3,  59,  42,  17,  62,  65,   8,  81,  45,  43,   6,  33,  68,
         8,  48, 200])

In [16]:
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [17]:
b

array([[51, 45, 86, 69],
       [73, 11, 44, 18],
       [93, 28, 64, 55],
       [95, 53, 96, 41],
       [80, 16, 23, 53],
       [ 7,  1, 37, 82]], dtype=int32)

In [18]:
b.shape

(6, 4)

In [19]:
np.random.random((b.shape[0], 1))

array([[0.24934851],
       [0.00470453],
       [0.15208158],
       [0.59401077],
       [0.98528062],
       [0.3564306 ]])

In [20]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[5.10000000e+01, 4.50000000e+01, 8.60000000e+01, 6.90000000e+01,
        6.87149423e-01],
       [7.30000000e+01, 1.10000000e+01, 4.40000000e+01, 1.80000000e+01,
        7.13943867e-01],
       [9.30000000e+01, 2.80000000e+01, 6.40000000e+01, 5.50000000e+01,
        3.55420745e-02],
       [9.50000000e+01, 5.30000000e+01, 9.60000000e+01, 4.10000000e+01,
        1.79257014e-01],
       [8.00000000e+01, 1.60000000e+01, 2.30000000e+01, 5.30000000e+01,
        1.48425318e-01],
       [7.00000000e+00, 1.00000000e+00, 3.70000000e+01, 8.20000000e+01,
        7.05793582e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [21]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [23]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [24]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [25]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [28]:
# code
a.shape

(15,)

In [30]:
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [32]:
f = np.expand_dims(a,axis=0)

In [33]:
f.shape

(1, 15)

In [37]:
np.expand_dims(a,axis=1)

array([[ 3],
       [59],
       [42],
       [17],
       [62],
       [65],
       [ 8],
       [81],
       [45],
       [43],
       [ 6],
       [33],
       [68],
       [ 8],
       [48]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [38]:
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [39]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  4,  5,  7, 12]),)

In [ ]:
# replace all values > 50 with 0
np.where(a>50,0,a)

In [40]:
np.where(a%2 == 0,0,a)

array([ 3, 59,  0, 17,  0, 65,  0, 81, 45, 43,  0, 33,  0,  0,  0],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [41]:
# code
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [42]:
np.argmax(a)

np.int64(7)

In [43]:
b

array([[51, 45, 86, 69],
       [73, 11, 44, 18],
       [93, 28, 64, 55],
       [95, 53, 96, 41],
       [80, 16, 23, 53],
       [ 7,  1, 37, 82]], dtype=int32)

In [44]:
np.argmax(b,axis=1)

array([2, 0, 0, 2, 0, 3])

In [45]:
np.argmax(b,axis=0)

array([3, 3, 3, 5])

In [ ]:
np.argmax(b,axis=1)

In [ ]:
a

In [46]:
# np.argmin
np.argmin(a)

np.int64(0)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [47]:
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [48]:
np.cumsum(a)

array([  3,  62, 104, 121, 183, 248, 256, 337, 382, 425, 431, 464, 532,
       540, 588])

In [50]:
b

array([[51, 45, 86, 69],
       [73, 11, 44, 18],
       [93, 28, 64, 55],
       [95, 53, 96, 41],
       [80, 16, 23, 53],
       [ 7,  1, 37, 82]], dtype=int32)

In [51]:
np.cumsum(b,axis=1)

array([[ 51,  96, 182, 251],
       [ 73,  84, 128, 146],
       [ 93, 121, 185, 240],
       [ 95, 148, 244, 285],
       [ 80,  96, 119, 172],
       [  7,   8,  45, 127]])

In [52]:
np.cumsum(b)

array([  51,   96,  182,  251,  324,  335,  379,  397,  490,  518,  582,
        637,  732,  785,  881,  922, 1002, 1018, 1041, 1094, 1101, 1102,
       1139, 1221])

In [54]:
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [57]:
np.cumprod(a)

array([                   3,                  177,                 7434,
                     126378,              7835436,            509303340,
                 4074426720,         330028564320,       14851285394400,
            638605271959200,     3831631631755200,   126443843847921600,
        8598181381658668800, -5001525241568856064,  -265538637080920064])

In [58]:
# np.cumprod
np.cumprod(a)

array([                   3,                  177,                 7434,
                     126378,              7835436,            509303340,
                 4074426720,         330028564320,       14851285394400,
            638605271959200,     3831631631755200,   126443843847921600,
        8598181381658668800, -5001525241568856064,  -265538637080920064])

In [59]:
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [60]:
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [67]:
np.percentile(a,50)

np.float64(43.0)

In [66]:
np.median(a)

np.float64(43.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [68]:
# code
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [71]:
np.sort(a)

array([ 3,  6,  8,  8, 17, 33, 42, 43, 45, 48, 59, 62, 65, 68, 81],
      dtype=int32)

In [70]:
np.histogram(a,bins=[0,20,30,40,50,100])

(array([5, 0, 1, 4, 5]), array([  0,  20,  30,  40,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [72]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [73]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [78]:
# code
a


array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [81]:
np.isin(a,[8,81])

array([False, False, False, False, False, False,  True,  True, False,
       False, False, False, False,  True, False])

In [82]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [83]:
# code
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [84]:
np.flip(a)

array([48,  8, 68, 33,  6, 43, 45, 81,  8, 65, 62, 17, 42, 59,  3],
      dtype=int32)

In [86]:
b

array([[51, 45, 86, 69],
       [73, 11, 44, 18],
       [93, 28, 64, 55],
       [95, 53, 96, 41],
       [80, 16, 23, 53],
       [ 7,  1, 37, 82]], dtype=int32)

In [87]:
np.flip(b,axis=1)

array([[69, 86, 45, 51],
       [18, 44, 11, 73],
       [55, 64, 28, 93],
       [41, 96, 53, 95],
       [53, 23, 16, 80],
       [82, 37,  1,  7]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [88]:
# code
a

array([ 3, 59, 42, 17, 62, 65,  8, 81, 45, 43,  6, 33, 68,  8, 48],
      dtype=int32)

In [89]:
np.put(a,[0,1],[110,530])

In [90]:
a

array([110, 530,  42,  17,  62,  65,   8,  81,  45,  43,   6,  33,  68,
         8,  48], dtype=int32)

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [91]:
# code
a

array([110, 530,  42,  17,  62,  65,   8,  81,  45,  43,   6,  33,  68,
         8,  48], dtype=int32)

In [92]:
np.delete(a,[0,2,4])

array([530,  17,  65,   8,  81,  45,  43,   6,  33,  68,   8,  48],
      dtype=int32)

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [94]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [95]:
np.intersect1d(m,n)

array([3, 4, 5])

In [96]:
np.setdiff1d(n,m)

array([6, 7])

In [97]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

In [ ]:
np.clip(a,a_min=25,a_max=75)

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals

In [99]:
a 

array([110, 530,  42,  17,  62,  65,   8,  81,  45,  43,   6,  33,  68,
         8,  48], dtype=int32)

In [100]:
np.clip(a,min=42,max=68)

array([68, 68, 42, 42, 62, 65, 42, 68, 45, 43, 42, 42, 68, 42, 48],
      dtype=int32)