### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

In [5]:
a = np.array([1,2,3,4,5,6])
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [34]:
# 2D and 3D
b = np.array([[[1,2,3],[4,5,6],[5,6,7]]])
print(b)

[[[1 2 3]
  [4 5 6]
  [5 6 7]]]


In [7]:
#tensor or 3D array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
# dtype
# np.array([1,2,3],dtype=float)
np.array([1,2,3,4,5], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j, 5.+0.j])

In [41]:
[i for i in range(1,7,2)]

[1, 3, 5]

In [43]:
# np.arange - just like range
# np.arange(1,11,2)

np.arange(1,21,2, dtype=float)

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19.])

In [ ]:
# with reshape
# np.arange(16).reshape(2,2,2,2) #4 D array
np.arange(24).reshape((2,2,6)) # 3 D array

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]],

       [[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]])

In [21]:
# np.ones and np.zeros
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [44]:
np.zeros((3,4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [52]:
# np.random
np.random.random((2,3,4,5))

array([[[[0.39272953, 0.38119459, 0.35137628, 0.71801409, 0.51900032],
         [0.47710808, 0.38170799, 0.59066869, 0.06413506, 0.77691306],
         [0.61388562, 0.7416173 , 0.81010685, 0.17752941, 0.13680877],
         [0.6867242 , 0.34072915, 0.39196086, 0.39013149, 0.85090391]],

        [[0.68640127, 0.24750379, 0.57325956, 0.34730514, 0.67534779],
         [0.63180679, 0.96712916, 0.55545094, 0.19091121, 0.26259166],
         [0.85028461, 0.80464399, 0.107005  , 0.31718222, 0.74862242],
         [0.40939787, 0.47295685, 0.9963517 , 0.3019556 , 0.25193977]],

        [[0.5343025 , 0.59881768, 0.28511671, 0.08540075, 0.65659672],
         [0.17658679, 0.10551002, 0.15102546, 0.27488044, 0.39228512],
         [0.87912876, 0.25821383, 0.2011116 , 0.64546609, 0.2868402 ],
         [0.88329327, 0.5152519 , 0.75329101, 0.05932411, 0.63278101]]],


       [[[0.14841559, 0.17438609, 0.34602824, 0.05270009, 0.59696395],
         [0.1199293 , 0.40335188, 0.72504343, 0.81028111, 0.53350911]

In [31]:
# np.linspace - linear space
np.linspace(-10,10,10,dtype=complex)

array([-10.        +0.j,  -7.77777778+0.j,  -5.55555556+0.j,
        -3.33333333+0.j,  -1.11111111+0.j,   1.11111111+0.j,
         3.33333333+0.j,   5.55555556+0.j,   7.77777778+0.j,
        10.        +0.j])

In [ ]:
# np.linspace(-10,10,10)

In [32]:
# np.identity -> identity matrix (diagonal is ones and rest are zeros)
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Array Attributes

In [82]:
a1 = np.arange(10,dtype=np.int32) #vector
a2 = np.arange(12,dtype=float).reshape(3,4) #matrix
a3 = np.arange(8).reshape(2,2,2) #tensor

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [83]:
# ndim -> number of dimensions
a3.ndim

3

In [84]:
# shape -> number of items in each dimension
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [85]:
# size -> total number of items
print(a2.size)
a2

12


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [86]:
# itemsize -> memory size for each item in bytes
a3.itemsize

8

In [87]:
# # dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


In [88]:
a1.dtype

dtype('int32')

### Changing Datatype

In [62]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

### Array Operations

In [63]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [70]:
# scalar operations

# arithmetic
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [75]:
# relational
a2 == 14

array([[False, False,  True, False],
       [False, False, False, False],
       [False, False, False, False]])

In [79]:
# vector operations
# arithmetic
a2 ** a1

array([[              1,              13,             196,
                   3375],
       [          65536,         1419857,        34012224,
              893871739],
       [    25600000000,    794280046581,  26559922791424,
        952809757913927]])

### Array Functions

[numpy functions link](https://numpy.org/doc/2.1/reference/routines.math.html)

In [4]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[36., 64., 76.],
       [ 0., 29., 21.],
       [24., 32., 19.]])

In [10]:
# max/min/sum/prod 
# 0 -> col and 1 -> row
np.prod(a1,axis=1)

array([175104.,      0.,  14592.])

In [18]:
# mean/median/std/var
np.mean(a1,axis=1)

array([58.66666667, 16.66666667, 25.        ])

In [19]:
# trigonomoetric functions
np.sin(a1)

array([[-0.99177885,  0.92002604,  0.56610764],
       [ 0.        , -0.66363388,  0.83665564],
       [-0.90557836,  0.55142668,  0.14987721]])

In [20]:
# dot product -> dot product between 2 matrices
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [22]:
# log and exponents
# np.exp(a1)
np.log(a1)

/tmp/ipykernel_6469/3962210963.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a1)


array([[3.58351894, 4.15888308, 4.33073334],
       [      -inf, 3.36729583, 3.04452244],
       [3.17805383, 3.4657359 , 2.94443898]])

In [28]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[31., 15., 12.],
       [77., 16., 69.]])

### Indexing and Slicing

In [29]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [30]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
a1[4:7:2]

array([4, 6])

In [46]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [51]:
a2[:, 3]

array([ 3,  7, 11])

In [52]:
a2[1,0]

np.int64(4)

In [57]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [59]:
a3[1,0,:]

array([4, 5])

In [60]:
a3[1,0,1]

np.int64(5)

In [61]:
a3[1,1,0]

np.int64(6)

In [63]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a1[2:5]

array([2, 3, 4])

In [68]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [69]:
a2[:,2]

array([ 2,  6, 10])

In [71]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [70]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [72]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

In [ ]:
a2[1,::3]

In [ ]:
a2[:2,1:]

In [ ]:
a2[0,:]

In [ ]:
a2[:,2]

In [ ]:
a2[1:,1:3]

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

In [ ]:
a3[::2,0,::2]

In [ ]:
a3[2,1:,1:]

In [ ]:
a3[0,1,:]

### Iterating

In [74]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [75]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [77]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [78]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [79]:
for i in np.nditer(a3):  #can be used for any number of dimensions
    print(i)

0
1
2
3
4
5
6
7


In [80]:
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [ ]:
# reshape


In [82]:
print(a2)
print(np.transpose(a2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [83]:
# Transpose
np.transpose(a2)
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [84]:
# ravel -> converts any dimension array to one D array
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

### Stacking -> shape must be same -> useful when combining data from multiple sources and stacking them together

In [ ]:
a4 = np.arange(12).reshape(3,4)
a5= np.arange(12,24).reshape(3,4)
a5

In [ ]:
np.hstack((a4,a5,a4,a5))

In [ ]:
np.vstack((a4,a5,a4,a5))

In [87]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [88]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [89]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [ ]:
# horizontal splitting -> opposite of stacking

In [90]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [94]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [95]:
np.hsplit(a4,5)

ValueError: array split does not result in an equal division

In [ ]:
# vertical splitting

In [96]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [100]:
np.vsplit(a5,3)

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [98]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division