### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([ 8, 97, 97, 92, 19, 14, 99, 49, 83, 38, 28, 14, 45,  3, 53])

In [25]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[10, 64, 27, 38],
       [23,  1, 96, 27],
       [43, 27, 60, 80],
       [23, 20, 58, 82],
       [93, 58, 31, 61],
       [79, 20, 55, 61]])

In [ ]:
np.sort(a)[::-1]

array([94, 92, 78, 68, 53, 50, 38, 37, 30, 28, 21, 11,  9,  5,  2])

In [ ]:
np.sort(b,axis=0)

array([[ 8, 18,  2,  6],
       [12, 52, 31,  7],
       [29, 63, 42,  9],
       [38, 71, 44, 55],
       [40, 87, 47, 72],
       [61, 93, 83, 85]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [ ]:
# code
np.append(a,200)

array([ 11,  53,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21, 200])

In [ ]:
b

array([[12, 52, 42,  6],
       [29, 18, 47, 55],
       [61, 93, 83,  9],
       [38, 63, 44, 85],
       [ 8, 87, 31, 72],
       [40, 71,  2,  7]])

In [ ]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[12.        , 52.        , 42.        ,  6.        ,  0.22006275],
       [29.        , 18.        , 47.        , 55.        ,  0.81740634],
       [61.        , 93.        , 83.        ,  9.        ,  0.89146072],
       [38.        , 63.        , 44.        , 85.        ,  0.84519124],
       [ 8.        , 87.        , 31.        , 72.        ,  0.24007274],
       [40.        , 71.        ,  2.        ,  7.        ,  0.48056374]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [17]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [22]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [26]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [27]:
# code
a.shape

(15,)

In [29]:
np.expand_dims(a,axis=0)

(1, 15)

In [30]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [33]:
np.expand_dims(a,axis=1)

array([[14],
       [11],
       [92],
       [51],
       [63],
       [65],
       [29],
       [44],
       [ 6],
       [86],
       [48],
       [66],
       [23],
       [88],
       [ 2]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [38]:
a

array([14, 11, 92, 51, 63, 65, 29, 44,  6, 86, 48, 66, 23, 88,  2])

In [35]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 2,  3,  4,  5,  9, 11, 13]),)

In [36]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([14, 11,  0,  0,  0,  0, 29, 44,  6,  0, 48,  0, 23,  0,  2])

In [37]:
np.where(a%2 == 0,0,a)

array([ 0, 11,  0, 51, 63, 65, 29,  0,  0,  0,  0,  0, 23,  0,  0])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [43]:
# code
a

array([14, 11, 92, 51, 63, 65, 29, 44,  6, 86, 48, 66, 23, 88,  2])

In [44]:
np.argmax(a)

2

In [45]:
b

array([[86,  8, 38, 25],
       [34, 74, 48, 50],
       [95, 61, 17, 79],
       [75, 38, 89, 21],
       [32, 54,  5, 46],
       [ 4, 41, 26, 65]])

In [47]:
np.argmax(b,axis=1)

array([0, 1, 0, 2, 1, 3])

In [ ]:
np.argmax(b,axis=0)

array([2, 2, 2, 3])

In [ ]:
np.argmax(b,axis=1)

array([1, 3, 1, 3, 1, 1])

In [49]:
a

array([14, 11, 92, 51, 63, 65, 29, 44,  6, 86, 48, 66, 23, 88,  2])

In [48]:
# np.argmin
np.argmin(a)

14

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [50]:
a

array([14, 11, 92, 51, 63, 65, 29, 44,  6, 86, 48, 66, 23, 88,  2])

In [51]:
np.cumsum(a)

array([ 14,  25, 117, 168, 231, 296, 325, 369, 375, 461, 509, 575, 598,
       686, 688])

In [55]:
b

array([[86,  8, 38, 25],
       [34, 74, 48, 50],
       [95, 61, 17, 79],
       [75, 38, 89, 21],
       [32, 54,  5, 46],
       [ 4, 41, 26, 65]])

In [57]:
np.cumsum(b,axis=1)

array([[ 86,  94, 132, 157],
       [ 34, 108, 156, 206],
       [ 95, 156, 173, 252],
       [ 75, 113, 202, 223],
       [ 32,  86,  91, 137],
       [  4,  45,  71, 136]])

In [ ]:
np.cumsum(b)

array([  12,   64,  106,  112,  141,  159,  206,  261,  322,  415,  498,
        507,  545,  608,  652,  737,  745,  832,  863,  935,  975, 1046,
       1048, 1055])

In [59]:
a

array([14, 11, 92, 51, 63, 65, 29, 44,  6, 86, 48, 66, 23, 88,  2])

In [58]:
np.cumprod(a)

array([                  14,                  154,                14168,
                     722568,             45521784,           2958915960,
                85808562840,        3775576764960,       22653460589760,
           1948197610719360,    93513485314529280,  6171890030758932480,
       -5620481882220965888,  3459684354712895488,  6919368709425790976])

In [ ]:
# np.cumprod
np.cumprod(a)

array([                  11,                  583,                16324,
                     816200,             31015600,           1147577200,
               107872256800,        9924247625600,       49621238128000,
           1488637143840000,   101227325781120000,   911045932030080000,
       -2725393596491966464, -5450787192983932928, -3786066610405281792])

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [4]:
a

array([20, 18, 88, 58, 48, 41, 89, 51, 76, 45, 43, 89, 59, 89, 32])

In [2]:
np.percentile(a,50)

45.0

In [3]:
np.median(a)

45.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [8]:
# code
a

array([ 8, 97, 97, 92, 19, 14, 99, 49, 83, 38, 28, 14, 45,  3, 53])

In [11]:
np.histogram(a,bins=[0,50,100])

(array([9, 6], dtype=int64), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [12]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

In [14]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [15]:
# code
a


array([ 8, 97, 97, 92, 19, 14, 99, 49, 83, 38, 28, 14, 45,  3, 53])

In [20]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [21]:
# code
a

array([ 8, 97, 97, 92, 19, 14, 99, 49, 83, 38, 28, 14, 45,  3, 53])

In [23]:
np.flip(a)

array([53,  3, 45, 14, 28, 38, 83, 49, 99, 14, 19, 92, 97, 97,  8])

In [26]:
b

array([[10, 64, 27, 38],
       [23,  1, 96, 27],
       [43, 27, 60, 80],
       [23, 20, 58, 82],
       [93, 58, 31, 61],
       [79, 20, 55, 61]])

In [30]:
np.flip(b,axis=1)

array([[38, 27, 64, 10],
       [27, 96,  1, 23],
       [80, 60, 27, 43],
       [82, 58, 20, 23],
       [61, 31, 58, 93],
       [61, 55, 20, 79]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [34]:
# code
a

array([110, 530,  97,  92,  19,  14,  99,  49,  83,  38,  28,  14,  45,
         3,  53])

In [ ]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [42]:
# code
a

array([110, 530,  97,  92,  19,  14,  99,  49,  83,  38,  28,  14,  45,
         3,  53])

In [45]:
np.delete(a,[0,2,4])

array([530,  92,  14,  99,  49,  83,  38,  28,  14,  45,   3,  53])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [56]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [57]:
np.intersect1d(m,n)

array([3, 4, 5])

In [58]:
np.setdiff1d(n,m)

array([6, 7])

In [59]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [60]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [61]:
# code
a

array([110, 530,  97,  92,  19,  14,  99,  49,  83,  38,  28,  14,  45,
         3,  53])

In [63]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 25, 25, 75, 49, 75, 38, 28, 25, 45, 25, 53])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals